### ISSUE TITLE
July：第二阶段工作重心：同步新的文章、指正&优化全部代码

### ISSUE THREAD

**Issue by julycoding** [julycoding/The-Art-Of-Programming-By-July#135]
很高兴，在github上与大家共同协作编程艺术系列，经过一个月的努力，咱们已经把大部分文章同步到本github上，然还有以下工作尚未完成（按优先级先后顺序排序）：
1、少部分新的文章尚未同步，如目录所示：https://github.com/julycoding/The-Art-Of-Programming-By-July/blob/master/ebook/zh/Readme.md
2、指正bug & 优化所有章节的代码
3、重绘图片：https://github.com/julycoding/The-Art-Of-Programming-By-July/issues/80
4、英文版翻译：部分章节已被认领https://github.com/julycoding/The-Art-Of-Programming-By-July/issues/84
5、添加其它语言如Java、python、go 的代码，放在ebook/code文件夹内（完成多少是多少）
6、写完后续的第42章~第50章

进入第2个月，除了继续完成上面尚未完成的事情外，咱们的工作重心为：同步完新的文章，优化所有章节的全部代码，保证代码质量。以上所有5个工作可以尽量在今年上半年之内完成。

OK，大家可以各自盯一章节，专门负责测试某一章的程序，保证基本无bug，若有能力，可以尽情优化代码，认领格式为：
“我同步第几章，预计某月之前完成”
或
“我负责指正&优化第某某章，预计某月之前完成”..

同时，欢迎邀请你身边coding质量高，可读性好，主写C/C++的朋友加入到咱们的队伍中。
辛苦各位，thanks。

**Comment by julycoding** [comment]
新书即将在今年2015年9月底上市。
感谢大家的共同努力。

**Comment by qiulp** [comment]
一直在关注中 给力 赞来自我的华为手机-------- 原始邮件 --------主题：Re: [The-Art-Of-Programming-By-July] July：第二阶段工作重心：同步新的文章、指正&优化全部代码 (#135)发件人：July 收件人：julycoding/The-Art-Of-Programming-By-July 抄送：新书即将在今年2015年9月底上市。
感谢大家的共同努力。
