### ISSUE TITLE
July：谁来一章一章的测试所有代码？

### ISSUE THREAD

**Issue by julycoding** [julycoding/The-Art-Of-Programming-By-July#210]
编程艺术系列 + 博客内其它部分经典文章的目录已经重新调整更新完毕，见：https://github.com/julycoding/The-Art-Of-Programming-By-July/blob/master/ebook/zh/Readme.md ，整个目录分为11章。

衡量文章质量有几个指标：是否通俗易懂，篇幅是否精简，程序代码是否有bug、代码风格是否良好，命名是否规范，代码逻辑 & 可读性是否良好，代码是否优化等等。

而其中，程序代码中若存在bug，则是令人厌恶的，故烦请大家一一认领这10章，一人一章，或一人1/2章，打开编译器一一测试每一章的代码，找出bug，指正错误。

认领格式为：
“我认领第某某章，预计某月某日排除此章的bug”。 

不要求你发现所有bug，尽你所能揪出你能揪出的bug即可，一章给一周到一个月的时间进行测试，如果发现bug，可以pull request，或在本issue 下指出，我来update 原文，thanks。

**Comment by julycoding** [comment]
新书即将在今年2015年9月底上市。
感谢大家的共同努力。

**Comment by zhaosoap** [comment]
@julycoding  你好，看了1.2 字符串包含 简单的一个题，给了四种解法。。
为什么不 直接开26个字符统计表  int['A'...'Z'],  对于每个字串字符 查表就行。 
求解答

**Comment by sg90** [comment]
解法四 就是这个思路






发自 Windows 邮件





发件人: zhaosoap
发送时间: ‎2015‎年‎9‎月‎2‎日, ‎星期三 ‎11‎:‎16
收件人: julycoding/The-Art-Of-Programming-By-July
抄送: sg90





@julycoding 你好，看了1.2 字符串包含 简单的一个题，给了四种解法。。
为什么不 直接开26个字符统计表 int['A'...'Z'], 对于每个字串字符 查表就行。 
求解答

**Comment by FuckFly** [comment]
呵呵呵
