### ISSUE TITLE
03.01 红黑树错误

### ISSUE THREAD

**Issue by zhuyifan2013** [julycoding/The-Art-Of-Programming-By-July#402]
插入修复情况1 和 2 的配图，在修改过后的图中都违背了红黑树的第四条性质，即：红色结点的两个儿子都必须为黑色。
不知是还没有i处理完全还是本身就有问题？

**Comment by julycoding** [comment]
@zhuyifan2013 ，你好，是没处理完
直到插入修复情况3 才处理完
所以插入修复1、2、3 连起来 才是一个完整的过程。
