### ISSUE TITLE
 [报错]render file error: API rate limit exceeded for 106.185.46.209

### ISSUE THREAD

**Issue by heroWang** [julycoding/The-Art-Of-Programming-By-July#413]
make html 报错.貌似是访问106.185.46.209频率太快导致的.

>$ make html
mkdir -p build/html
cp -r ../images/ build/images
cp TAOP.png build/html
62  files in render list...
1 / 62 :  Rendering:  e:\HOME\Git\The-Art-Of-Programming-By-July\ebook\zh\00.01.md Error:  render file error: API rate limit exceeded for 106.185.46.209. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
Makefile:32: recipe for target 'build/html/TAOP_July.html' failed
make: *** [build/html/TAOP_July.html] Error 1

Google之后找到这样一个页面<https://developer.github.com/v3/>.应该是访问API时没有登陆导致的**403 Forbidden**

**Comment by marchtea** [comment]
这个需要添加上你的github账号和密码。可以修改makefile，有个GHUSER，GHPASS两个变量，修改为你的账号和密码，就可以了。
