### ISSUE TITLE
看到好几章的节序号会跳跃，这是为什么？

### ISSUE THREAD

**Issue by ssjssh** [julycoding/The-Art-Of-Programming-By-July#416]
比如第一章从1.6到1.10，中间的章节是被删除了还是因为保护版权的原因？
如果是因为保护版权，希望先出个电子版。可以放在豆瓣或者亚马逊上。

**Comment by Boshen** [comment]
这个线上版本好像已经停止更新了，所有修改他们都在线下更改了。。
