### ISSUE TITLE
01.01.md中的一张图片问题，不知是否已经修改

### ISSUE THREAD

**Issue by jmmyy** [julycoding/The-Art-Of-Programming-By-July#420]
这张图片中有个错别字，`同意平面`应为`同一平面`
![qq 20150507200947](https://cloud.githubusercontent.com/assets/10357476/7514948/1054c172-f4f5-11e4-95aa-ccc3311afeac.png)

**Comment by julycoding** [comment]
谢谢反馈
这张图片在最新的书稿中已经删除。
有何其它任何问题，欢迎继续反馈。
