### ISSUE TITLE
请问下啊 什么时候可以购买啊啊？

### ISSUE THREAD

**Issue by jinjingcai2014** [julycoding/The-Art-Of-Programming-By-July#422]
从14年在csdn上看见了，一直等着购买呢，坐等中ing

**Comment by julycoding** [comment]
你好
《编程之法》纸质版已于2015年10月14日陆续开卖！目前，京东、当当、亚马逊等各大网店均已有现货销售。

京东：http://item.jd.com/11786791.html 。
当当：http://product.dangdang.com/23796222.html 。

新书《编程之法：面试和算法心得》的勘误在此文最末：http://blog.csdn.net/v_july_v/article/details/49302193

感谢你的关注
