### ISSUE TITLE
纸质版出版后会有什么区别？

### ISSUE THREAD

**Issue by zhaoweiwang** [julycoding/The-Art-Of-Programming-By-July#433]
RT

**Comment by julycoding** [comment]
纸质版在本github上的基础上做了极大彻底的改进、优化，无论是完整度、还是最新度、或质量上，都远非博客、github所能相比。
目前新书正在印刷中，十一后陆续上架各大网店，10月10日左右能买到手。

**Comment by zhaoyta** [comment]
举一反三也有实现了吗

在 2015年9月29日 下午2:17，July <notifications@github.com>写道：

> 纸质版在本github上的基础上做了极大彻底的改进、优化，无论是完整度、还是最新度、或质量上，都远非博客、github所能相比。
> 目前新书正在印刷中，十一后陆续上架各大网店，10月10日左右能买到手。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/julycoding/The-Art-Of-Programming-By-July/issues/433#issuecomment-143956795>
> .
>



--

**Comment by zhaoweiwang** [comment]
前两天买了左大刚出的书，略微失望，一点是用了java非c/c++；另一个是写的条理并不是很清晰。还是比较期待您的作品，坐等

**Comment by julycoding** [comment]
我新书最基本的特征之一是：逻辑清晰、通俗易懂。

**Comment by Forrest-Liu** [comment]
会有kindle版本吗

**Comment by julycoding** [comment]
kindle版本暂时不推出。

**Comment by zhaoweiwang** [comment]
用C/C++风格还是Java呢

**Comment by julycoding** [comment]
主要C/C++，极少量Java。

**Comment by julycoding** [comment]
yeah yeah
我的新书《编程之法》终于在2015年10月14日上架开卖了！抢购地址：http://www.epubit.com.cn/book/details/4051 。后面会陆续上架京东、当当、亚马逊、互动出版网等各大网店。

**Comment by jac0320** [comment]
会有电子版出售么？在海外不太方便买纸质版

On Wed, Oct 14, 2015 at 11:49 AM, July <notifications@github.com> wrote:

> yeah yeah
> 我的新书《编程之法》终于在2015年10月14日上架开卖了！抢购地址：
> http://www.epubit.com.cn/book/details/4051 。后面会陆续上架京东、当当、亚马逊、互动出版网等各大网店。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/julycoding/The-Art-Of-Programming-By-July/issues/433#issuecomment-148092520>
> .
>



-- 

Site Wang, M. S.
PhD Student, Department of Industrial Engineering
Clemson University
Freeman Hall
Clemson, SC
29634
United States

**Comment by RongLi1986** [comment]
人在海外，不知该如何购买此书？？可有电子版销售么？

**Comment by RongLi1986** [comment]
人在海外，如何购买此书？？可有电子版？？

**Comment by taobit** [comment]
如果上架京东，能不能让京东海外版也能买得到此书？那我就可以买到了，本人在美国

**Comment by julycoding** [comment]
抱歉，目前没有电子版，只有纸质版在销售：http://www.epubit.com.cn/book/details/4051

**Comment by jmychou** [comment]
@zhaoweiwang java版书名是？？

**Comment by julycoding** [comment]
新书主要C实现，目前当当、互动、异步皆有售。很快上架京东、亚马逊。
