### ISSUE TITLE
勘误，书21页，逻辑错误

### ISSUE THREAD

**Issue by yanggeorge** [julycoding/The-Art-Of-Programming-By-July#442]
‘’当mx - i > P[i]的时候，以S［j］为中心。。。¨
这里应该是S［i］，
由于i与j对称，以S［j］为中心，这样才符合叙述的逻辑。

**Comment by hammersmith-xie** [comment]
书21页第二段，july在后半段提到了“由于i和j对称，以S[i]为中心的回文子串必然被包含在...”，july多写了一段对称，方便理解。你所说的意思，july已经表达出来了。

**Comment by yanggeorge** [comment]
逻辑堪忧啊

**Comment by yanggeorge** [comment]
说实话，书的质量和获得的赞誉差的很远。还是太浮躁。好好看看日本人写的书吧，比如30天自制操作系统，等图灵书。

**Comment by nakamura343** [comment]
能说告诉我一下那本30天自作系统的书，具体名字吗？或者作者也行。想找来看看。谢谢

发自我的 iPhone ◉

**Comment by yanggeorge** [comment]
@nakamura343 http://www.ituring.com.cn/book/910

**Comment by yanggeorge** [comment]
可能出版社不行，对科技书籍没有比较的审美。

**Comment by yanggeorge** [comment]
中国人写的书大部分仍然显示出功力不够。经典的算法书都是浑然一体的。因为作者真的吃透了，融汇贯通了。反观国人的书，总是体现一个“编”字。

**Comment by nakamura343** [comment]
果然是这本。谢谢。
这本书写的很好吗？买本来看看。正好我会日语。

发自我的 iPhone ◉

**Comment by yanggeorge** [comment]
@nakamura343 汗，中文的质量还可以了。我看的中文。

**Comment by cpcs** [comment]
应该没问题？ i, j对称的

**Comment by recq-cse** [comment]
这书质量不要太差

**Comment by v1-hermit** [comment]
[百毒、免费](https://pan.baidu.com/s/1_Flf73uiMMuVrjqvHd4VNA)

**Comment by julycoding** [comment]
已确认，这里没问题，i, j对称的
