### ISSUE TITLE
July：准备重绘所有的图片，大家来认领分工拉

### ISSUE THREAD

**Issue by julycoding** [julycoding/The-Art-Of-Programming-By-July#80]
本编程艺术系列，需要重绘所有的图片，如果哪位朋友画的图比较专业点，欢迎认领。

可以考虑使用的工具：①TikZ - 通吃各种绘图，依赖 LaTeX ，需要LaTeX基础；②Asymptote -通吃各种绘图，甚至可以绘制3D，语法类似 OpenGL ；③Graphviz - 线、框图；④Visio；⑤简单的图也可以直接上 ASCII 图；

大家更喜欢用哪一种工具画图？欢迎都发表下意见，如：
我喜欢用TikZ..

如果能统一用同一种画图工具最好，如果各自喜欢各自的画图工具也没关系，咱们先画画看，认领的格式为：
我来画第1-5章的图，用TikZ画，预计在某月某日之前完成..

thanks。

**Comment by julycoding** [comment]
新书即将在今年2015年9月底上市。
感谢大家的共同努力。

**Comment by GitLLTT** [comment]
去
